### ISSUE TITLE
Filter posts to Mastodon by template?

### ISSUE THREAD

**Issue by kevquirk** [mauricerenck/indieConnector#11]
This looks really good and I'm thinking about implementing it on my site for publishing to Masto, but I wouldn't want all pages I publish to be pushed.

For example, if I create a new terms & conditions page (ewww) I wouldn't want that posted on Masto. I imagine most folk would just want certain types of page posting, like blog posts or notes for example.

I can't see anything in the documentation that talks about this. Does such a feature exist, or is it on the roadmap?

Thanks,

Kev

**Comment by mauricerenck** [comment]
Hi Kev,

you are right, this is currently not possible, but it's indeed on the roadmap. There is a major release in the making with granular "moderation" tools, like blocking domains and also more functions for Mastodon, like setting which template may send to Mastdon and a setting on page level for disabling sending on a certain page.

I'll flag this as a feature to keep me reminded and ping you here, if the release is ready.

Maurice

**Comment by kevquirk** [comment]
Fantastic, thanks Maurice!
