### ISSUE TITLE
Posting to Bluesky gives undefined array key error

### ISSUE THREAD

**Issue by mbrtltt** [mauricerenck/indieConnector#15]
Posting to Mastodon works as expected, but posting to Bluesky throws an error. Tested in a fresh starter kit installation with only IndieConnector 2.2.0 installed, with `config.php` edited only to enable posting to Bluesky using the code [provided in the docs](https://github.com/mauricerenck/indieConnector/blob/main/docs/mastodon.md#bluesky), changing a page from Draft to Public gives an error `Undefined array key 1`
![error](https://github.com/user-attachments/assets/4aaef8e8-a13a-42b3-81a2-3572267df286)
Doesn't appear that any other info is available in the error log.

**Comment by mauricerenck** [comment]
Thank you for reporting, this was an error in the external bluesky library. Luckily they already fixed it.
