### ISSUE TITLE
Some webmention.rocks tests are failing

### ISSUE THREAD

**Issue by srijan** [mauricerenck/indieConnector#9]
I tested this plugin with the validator at [webmention.rocks](https://webmention.rocks) and most tests passed!

But these tests failed:

  * Discovery test 23: [https://webmention.rocks/test/23](https://webmention.rocks/test/23)
  * Update test 2: [https://webmention.rocks/update/2](https://webmention.rocks/update/2)
  * Delete test 1: [https://webmention.rocks/delete/1](https://webmention.rocks/delete/1)

(Originally published at: https://srijan.ch/notes/2023-11-03-002)

**Comment by mauricerenck** [comment]
Thank you for noting.
I will have a look at the discovery test.

Both, update and delete, are missing features at the moment. They are on my list.
